name: Deploy to EC2 and Install k3s

on:
  push:
    branches:
      - main
    paths:
      - 'website3.0/**'  # Runs only when changes are made in website3.0 folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Current Version
        id: versioning
        run: |
          if [ -f version.txt ]; then
            VERSION=$(cat version.txt)
          else
            VERSION=v0  # Default to v0 if file doesn't exist
          fi
          NEW_VERSION="v$(( ${VERSION//[!0-9]/} + 1 ))"
          echo $NEW_VERSION > version.txt
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit Updated Version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Bump version to ${VERSION}"
          git push origin main

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/helpops:${VERSION} ./website3.0
          docker push ${{ secrets.DOCKER_USERNAME }}/helpops:${VERSION}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: deploy on k3s 
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem
          # Install k3s on the EC2 instance
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            curl -sfL https://get.k3s.io | sh -
            sudo systemctl enable k3s
            sudo systemctl start k3s
            sudo kubectl get nodes
          EOF

      - name: Set up kubectl for k3s
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo cat /etc/rancher/k3s/k3s.yaml > kubeconfig.yaml
            echo "KUBECONFIG=$(cat kubeconfig.yaml)" >> $GITHUB_ENV
          EOF

      - name: Get Latest Version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Update Image Tag in Deployment
        run: |
          sed -i "s|image: mayaworld13/helpops:.*|image: mayaworld13/helpops:${VERSION}|" k8s/deployment.yml

      - name: Apply Kubernetes Deployment
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl cluster-info
          kubectl apply -f k8s/deployment.yml

      - name: Restart Deployment
        run: kubectl rollout restart deployment nextjs-app
