name: Deploy to AWS EC2 with Docker-Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Docker App to AWS EC2 via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Add the SSH private key to the agent
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # Connect to EC2 and run deployment commands
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Navigate to project folder and pull latest changes
            
            cd /home/ubuntu/helpops
            kubectl apply -f deployment.yml

            
            
            
          EOF

      - name: Clean Up SSH Key
        run: rm -f private_key.pem
